module br { module pucrio { module tecgraf { module springboot { module openbus {

interface ServiceOperations1 {
    string greetsOne();
};


interface ServiceOperations2 {
    string greetsTwo();
};

interface ServiceOperations3 {
    string greetsThree();
};

}; }; }; }; };